String jsondata = '''{
   "value":309817309430.12,
   "accounts":[
      {
         "name":"ubs15",
         "value":23924800.8,
         "positions":[
            {
               "name":"fixedIncomeCash",
               "value":20000000
            },
            {
               "name":"equities",
               "value":13884803082.0,
               "positions":[
                  {
                     "name":"glencore",
                     "shares":90000,
                     "pricePer":4.72,
                     "value":424800
                  },
                  {
                     "name":"bawsaq",
                     "shares":40200,
                     "pricePer":9.41,
                     "value":378282
                  },
                  {
                     "name":"ATEEZ",
                     "shares":200000000,
                     "pricePer":69.42,
                     "value":13884000000
                  }
               ]
            },
            {
               "name":"credit",
               "value":2500000,
               "positions":[
                  {
                     "name":"avenueAviation",
                     "value":1000000
                  },
                  {
                     "name":"rialto",
                     "value":1500000
                  }
               ]
            },
            {
               "name":"hedgefund",
               "value":1000000,
               "positions":[
                  {
                     "name":"blackRockEU",
                     "value":1000000
                  }
               ]
            }
         ]
      }
   ]
}
''';
